version: '3'
services:

  postgres:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: elestio/pgadmin:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=cosima_hiromi.zink@smail.th-koeln.de
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=8080
    ports:
      - "9001:8080"

  springboot:
    build:
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data: