version: '3'
services:

  postgres:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data


  springboot:
    build:
      dockerfile: Dockerfile
    container_name: springboot-app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
    ports:
      - "8080:8080"